In [2]:
import pandas as pd
Datensatz = pd.read_csv('boston_2019.csv', sep=',')

In [5]:
Datensatz.head(6)

,start_time,end_time,start_station_id,end_station_id,start_station_name,end_station_name,bike_id,user_type
0,2019-01-01 00:09:13.7980,2019-01-01 00:15:25.3360,80,179,MIT Stata Center at Vassar St / Main St,MIT Vassar St,3689,Subscriber
1,2019-01-01 00:33:56.1820,2019-01-01 00:38:20.8800,117,189,Binney St / Sixth St,Kendall T,4142,Subscriber
2,2019-01-01 00:41:54.6000,2019-01-01 00:49:33.2730,68,96,Central Square at Mass Ave / Essex St,Cambridge Main Library at Broadway / Trowbridg...,1628,Subscriber
3,2019-01-01 00:43:32.5710,2019-01-01 00:49:37.4260,89,334,Harvard Law School at Mass Ave / Jarvis St,Mass Ave at Hadley/Walden,2969,Subscriber
4,2019-01-01 00:49:56.4640,2019-01-01 01:01:17.7010,73,367,Harvard Square at Brattle St / Eliot St,Vassal Lane at Tobin/VLUS,3469,Subscriber
5,2019-01-01 00:50:01.0370,2019-01-01 00:59:10.3190,104,76,Harvard University Radcliffe Quadrangle at She...,Central Sq Post Office / Cambridge City Hall a...,4050,Customer